apiVersion: v1
kind: Secret
metadata:
  name: frontend-ordering-secret
  namespace: web-ui
type: Opaque
data:
  # ⚠️ สำคัญ: ค่าใน Secret ต้องถูกเข้ารหัสด้วย Base64 เสมอ
  # (พิมพ์ใน Terminal: echo -n "my-secret-token" | base64)
  STRIPE_SECRET_KEY: c2tfdGVzdF81MVNCWGwyOGlxdm40Wjdia1pOUnFkdnRBdHZjdU1iZ0NSRTR5VkFYVTBCN1QzV1NROG5QZU1wTUdlQWxqalB5cklyajVGRW9VWW1uNzNWa21GVHFibldnWDAwVUYzVjN6Y3Y=
  STRIPE_PUBLIC_KEY: cGtfdGVzdF81MVNCWGwyOGlxdm40Wjdia1hmQ0pza2FZZmI3R2VBblRObVN3RmQ5WEo1bFJ4U1hPMkVnYUhUc1JObFVCMUQ4ZThMQmpjZllzVElvb2s1cVA5Y3hWOUNsazAwQzE1aW5oaWI=