apiVersion: v1
kind: Service
metadata:
  name: frontend-ordering-service
  namespace: web-ui
  labels:
    app: frontend-ordering-service
spec:
  type: ClusterIP
  selector:
    app: frontend-ordering
    
  ports:
    - name: http
      port: 80
      targetPort: 3000